name: Build Resume PDF

on:
    push:
        branches: 
          - main
          - feat/ci_cd

jobs:
    build_pdf:
        runs-on: ubuntu-latest
        steps:
          - name: "Check out repository code"
            uses: actions/checkout@v4

          - name: Set up TeX Live
            uses: zauguin/install-texlive@v4
            with:
              packages: >
                context 
                luatex 
                latex 
                fonts-recommended
                fonts-extra

          
          - name: Setup Pandoc
            uses: pandoc/actions/setup@v1
          
          - name: "Run Pandoc to Generate Tex Files"
            run: |
              for f in _includes/input_documents/*.md; do
                FILE_NAME=`basename $f | sed 's/.md//g'`;
                pandoc $f --standalone \
                --from markdown --to context \
                --template pandoc-builder-scripts/styles/green_template.tex \
                --variable papersize=A4 \
                --output external_documents/output/$FILE_NAME.tex;
              done
          
          - name: "Run ConTeXt to Generate PDF"
            run: |
              for f in external_documents/output/*.tex; do
                FILE_NAME=`basename $f | sed 's/.tex//g'`;
                mtxrun --path=external_documents/output \
                --result=$FILE_NAME.pdf \
                --script context $FILE_NAME.tex > external_documents/logs/context_$FILE_NAME.log 2>&1;
              done
          
          - name: "Commit and Push"
            run: |
              git config --global user.name "github-actions[bot]"
              git config --global user.email "github-actions[bot]@users.noreply.github.com"
              git add external_documents/output/
              git diff-index --quiet HEAD || git commit -m "Add generated PDF file"
              git push

          - name: Push Artifact
            uses: actions/upload-artifact@v4
            with:
              name: pdf-test 
              path: external_documents/ 
              retention-days: 1

          - name: Push Error
            if: failure()
            uses: actions/upload-artifact@v4
            with:
                name: failure-logs
                path: |
                  /home/runner/texlive/texmf-var/web2c/
                  external_documents/logs/
                  
